name: 'Settings Tray'
type: module
description: 'Provides a sidebar to configure blocks on the page.'
package: Core
<<<<<<< HEAD
# version: VERSION
# core: 8.x
=======
version: VERSION
core: 8.x
>>>>>>> 9a70c99dc372ded3fe684a74ceb1086713a7c931
dependencies:
  - block
  - toolbar
  - contextual

# Information added by Drupal.org packaging script on 2018-04-25
version: '8.5.3'
core: '8.x'
project: 'drupal'
datestamp: 1524673226
